"""Add agencies table and user agency relationship

Revision ID: 87b536a02c06
Revises: 
Create Date: 2025-06-14 22:21:49.613709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87b536a02c06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_applications_id', table_name='applications')
    op.drop_table('applications')
    op.alter_column('agencies', 'license_expiry',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_column('agencies', 'updated_at')
    op.drop_column('agencies', 'created_at')
    op.add_column('users', sa.Column('agency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'agencies', ['agency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'agency_id')
    op.add_column('agencies', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('agencies', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('agencies', 'license_expiry',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_table('applications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('applicant_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cv_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cover_letter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('appliedDate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='applications_job_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='applications_pkey')
    )
    op.create_index('ix_applications_id', 'applications', ['id'], unique=False)
    # ### end Alembic commands ###
