"""Add phone no  employer inquiries table

Revision ID: 9b42707d6d12
Revises: a6ada102d378
Create Date: 2025-06-15 13:59:45.340729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b42707d6d12'
down_revision: Union[str, None] = 'a6ada102d378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employer_inquiries', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('employer_inquiries', sa.Column('is_urgent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employer_inquiries', 'is_urgent')
    op.drop_column('employer_inquiries', 'phone_number')
    # ### end Alembic commands ###
